export const metadata = {
    title: 'Welcome About Page',
    description: 'Generated by create next app',
  }


export default function AboutLayout({ children }) {
    return (
    <div>
        <main>
            {children}
        </main>
    </div>
  )
}
